[package]
name = "typst-preprocess"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prequery-preprocess"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive", "env"] }
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
toml = "0.8.14"
